apiVersion: v1
kind: Pod
metadata:
  name: rotation-demo-worker-go
  labels:
    app: rotation-demo-worker-go
spec:
  containers:
  - name: rotation-demo-worker-go
    image: pvsone/rotation-demo-worker-go:1.0.0
    volumeMounts:
    - name: tls-volume
      mountPath: /certs
      readOnly: true
    env:
    - name: TEMPORAL_ADDRESS
      value: "rotation-demo.sdvdw.tmprl.cloud:7233"
    - name: TEMPORAL_NAMESPACE
      value: "rotation-demo.sdvdw"
    - name: TEMPORAL_TLS_CERT
      value: /certs/tls.crt
    - name: TEMPORAL_TLS_KEY
      value: /certs/tls.key
  volumes:
  - name: tls-volume
    csi:
      readOnly: true
      driver: csi.cert-manager.io
      volumeAttributes:
        csi.cert-manager.io/issuer-name: rotation-demo-ca-issuer
        csi.cert-manager.io/common-name: rotation-demo-worker
        csi.cert-manager.io/duration: 5m
        csi.cert-manager.io/fs-group: "1000"
